# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Person.create([ {full_name: "Mary Toft", link: "http://en.wikipedia.org/wiki/Mary_Toft", bio_count: 5}, {full_name: "Oscar the Cat", link: "http://en.wikipedia.org/wiki/Oscar_%28therapy_cat%29", bio_count: 5}, {full_name: "George P. Burdell", link: "http://en.wikipedia.org/wiki/George_P._Burdell"}, {full_name: "Aron Ralston", link: "http://en.wikipedia.org/wiki/Aron_Ralston"}, {full_name: "Larry Walters", link: "http://en.wikipedia.org/wiki/Larry_Walters"}, {full_name: "Howard Hallis", link: "http://en.wikipedia.org/wiki/Howard_Hallis"}, {full_name: "Rosemary Brown", link: "http://en.wikipedia.org/wiki/Rosemary_Brown_%28spiritualist%29"}, {full_name: "Joyce Hatto", link: "http://en.wikipedia.org/wiki/Joyce_Hatto"}, {full_name: "Jerry Haleva", link: "http://en.wikipedia.org/wiki/Jerry_Haleva"}, {full_name: "Michael Larson", link: "http://en.wikipedia.org/wiki/Michael_Larson"}, {full_name: "John Titor", link: "http://en.wikipedia.org/wiki/John_Titor"}, {full_name: "Charles Domery", link: "http://en.wikipedia.org/wiki/Charles_Domery"} ])
Bio.create([ {text: "A woman who tricked doctors into believing that she had given birth to rabbits.", real: true, person_id: 1}, {text: "[INSERT].", real: false, person_id: 1}, {text: "[INSERT].", real: false, person_id: 1}, {text: "[INSERT].", real: false, person_id: 1}, {text: "[INSERT].", real: false, person_id: 1}, {text: "A hospice cat who was featured in the New England Journal of Medicine for his purported ability to predict the impending death of terminally ill patients.", real: true, person_id: 2}, {text: "[INSERT].", real: false, person_id: 2}, {text: "[INSERT].", real: false, person_id: 2}, {text: "[INSERT].", real: false, person_id: 2}, {text: "[INSERT].", real: false, person_id: 2}, {text: "A fictitious student officially enrolled at Georgia Tech in 1927, who has been continuously enrolled at the school ever since.", real: true, person_id: 3}, {text: "One tough guy who, to escape from death, cut off his own arm with a dull knife after a boulder fell on it.", real: true, person_id: 4}, {text: "Successfully piloted a lawn chair to 16,000 feet over Los Angeles.", real: true, person_id: 5}, {text: "An artist who attempted to draw a massive painting containing drawings of thousands of people and items, both real and imaginary.", real: true, person_id: 6}, {text: "A spiritualist who claimed that dead composers dictated new musical works to her.", real: true, person_id: 7}, {text: "A pianist who had many doctored recordings falsely attributed to her long after she stopped performing in public.", real: true, person_id: 8}, {text: "A man who got a film acting career solely based on his resemblance to Saddam Hussein.", real: true, person_id: 9}, {text: "A man who won over $100,000 in an episode of Press Your Luck because he was able to notice a pattern in the flashing lights on the Big Board.", real: true, person_id: 10}, {text: "The name of a purported time traveler from the year 2036.", real: true, person_id: 11}, {text: "A Polish soldier noted for his unusually large appetite. While imprisoned in England, he remained ravenous despite being put on ten times the rations of other inmates, eating the prison cat, at least twenty rats and, on a regular basis, the prison candles.", real: true, person_id: 12} ])
User.create([{email: "peter@example.com", password: "password", password_confirmation: "password"}, {email: "joe@example.com", password: "password", password_confirmation: "password"}])